### ISSUE TITLE
FATAL: List error: request canceled while waiting for connection

### ISSUE THREAD

**Issue by saper** [repbin/repbin#23]
$ repclient -index -server http://my-server.onion
Private key(s):  
Specific server

FATAL: List error: Get http://my-server.onion/keyindex?key=some-key&start=0&count=10: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

The destination server is empty - there was one message to this recipient, but it expired.

The server has only the usual messages and is reachable via Tor (i.e. the internal web server returns my customized page).

**Comment by saper** [comment]
After minute or two it went back to normal. I have issues two `-peerlist` requests in between: the first returned `FATAL: Peer discovery failed: client: No peers`, and the second one returned normal output.
After this checking `-index` worked as well.

**Comment by RyanPear** [comment]
The original error indicates that the connection through the Tor SOCKS proxy timed out or was closed. This happens when trying to reach a hidden service that is not routable, or if the connection to the tor network of either client or server has failed. If this error appears consistently than there is an issue with either the port/url configuration or with the network connection to Tor nodes itself.

**Comment by saper** [comment]
Thanks, this explains the situation.
